### Get all inspections from HNB
GET {{api_url}}/inspection
TENANT: hnb

### Get all inspections from INME
GET {{api_url}}/inspection
TENANT: inme

### Get all inspections from Invalid Tenant
GET {{api_url}}/inspection
TENANT: inme2

### Create new inspection
POST {{api_url}}/inspection
Content-Type: application/json
TENANT: hnb

{
  "type": "OFS",
  "policyNumber": "LKDJFSIOJ",
  "policyHolder": "Testing 123"
}
